events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  upstream us_servers {
    server us-app1:3000;
    server us-app2:3001;
  }

  server {
    listen 80;

    location /uploads/ {
      alias /app/uploads/;
      add_header Cache-Control "public, max-age=604800, immutable";
      add_header Vary "Accept-Encoding";
    }

    location / {
      proxy_pass http://us_servers;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Region "us-east";
      add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
  }
}