events {
  worker_connections 1024;
}

http {
  upstream nodejs_servers {
    server app1:3000;
    server app2:3001;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://nodejs_servers;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}